version: '3.8'

services:
  # Lightweight Database
  postgres:
    image: postgres:15
    container_name: hypatia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hypatia_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Lightweight Cache
  redis:
    image: redis:7-alpine
    container_name: hypatia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Lightweight Message Queue (using Redis instead of Kafka for simplicity)
  redis-streams:
    image: redis:7-alpine
    container_name: hypatia-events
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - events_data:/data
    command: redis-server --appendonly yes --port 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  events_data:
    driver: local

networks:
  default:
    name: hypatia-network
    driver: bridge
